spring:
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
